### ISSUE TITLE
how can i implementing this library

### ISSUE THREAD

**Issue by pishguy** [pdliuw/airoute#2]
could you help me how can i implementing this library on my project?

i get error and i can't resolve that

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Builder:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1578 pos 16: 'observer.navigator == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  StartupApplication file:///C:/Users/mahdi/AndroidStudioProjects/unlimited_power_pro/lib/main.dart:39:70
When the exception was thrown, this was the stack: 
#2      NavigatorState.didUpdateWidget (package:flutter/src/widgets/navigator.dart:1578:16)
#3      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
...
```

my implemented code:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Provider.debugCheckInvalidValueType = null;

  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]).then((_) {
    runApp(MultiProvider(providers: providers, child: OKToast(child: StartupApplication())));
  });
}

class StartupApplication extends StatefulWidget {
  StartupApplication() {
    Navigation.initRoutes();
  }

  @override
  _StartupApplicationState createState() => _StartupApplicationState();
}

class _StartupApplicationState extends State<StartupApplication> {
  @override
  Widget build(BuildContext context) {
    return Airoute.createMaterialApp(
      title: Fa.appName,
      theme: ThemeData(
        fontFamily: 'IranSansLight',
        primaryColor: Color(0xFF823A84),
        accentColor: Color(0xFF823A84),
        textTheme: TextTheme(title: TextStyle(fontFamily: 'IranSansLight', color: Colors.black)),
      ),
      home: Directionality(
          textDirection: TextDirection.rtl,
          ),
      routes: <String, AirouteBuilder>{
        "/showDocumentContent": () => ShowDocumentContent(),
      },
    );
  }
}
```

**Comment by pdliuw** [comment]
What does this line of code do?

```
    Navigation.initRoutes();
```

class StartupApplication extends StatefulWidget {
  StartupApplication() {
    Navigation.initRoutes();
  }

  @override
  _StartupApplicationState createState() => _StartupApplicationState();
}

**Comment by pdliuw** [comment]
Regarding this issue, I checked again, airoute can be used normally. 

Preliminary conclusion: I can't know more about Navigation.initRoutes (); 

but I don't recommend using "airoute" and "other routes at the same time in the application. "

If you are willing to provide more information about: Navigation.initRoutes () ;, we will further investigate your routing conflicts

**Comment by pishguy** [comment]
after removing others routes i get error again:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Provider.debugCheckInvalidValueType = null;

  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]).then((_) {
    runApp(MultiProvider(providers: providers, child: OKToast(child: StartupApplication())));
  });
}
}

class StartupApplication extends StatefulWidget {
  @override
  _StartupApplicationState createState() => _StartupApplicationState();
}

class _StartupApplicationState extends State<StartupApplication> {
  @override
  Widget build(BuildContext context) {
    return Airoute.createMaterialApp(
      title: Fa.appName,
      theme: ThemeData(
        fontFamily: 'IranSansLight',
        primaryColor: Color(0xFF823A84),
        accentColor: Color(0xFF823A84),
        textTheme: TextTheme(title: TextStyle(fontFamily: 'IranSansLight', color: Colors.black)),
      ),
      home: Directionality(),
      routes: <String, AirouteBuilder>{
        "/home": () => Home(),
        "/lesson": () => LessonsPage(),
        "/play": () => LessonDetail(),
        "/certificateOfDisclaimer": () => LessonsCertificateOfDisclaimer(),
        "/tickets": () => Tickets(),
        "/keywords": () => Keywords(),
        "/faq": () => Faq(),
        "/aboutUs": () => AboutUs(),
        "/contactUs": () => ContactUs(),
        "/serviceRole": () => ServiceRole(),
        "/showLessonParts": () => ShowLessonParts(),
        "/main_route": () => MainRoute(),
        "/pageConceptsInformation": () => ShowPageConceptsInformation(),
        "/pageLessonsDescription": () => ShowPageLessonsDescription(),
        "/profileCode": () => ProfileCode(),
        "/market": () => Market(),
        "/results": () => Results(),
        "/documents": () => Documents(),
        "/lessonDescription": () => LessonDescription(),
        "/monthDescription": () => MonthDescription(),
        "/readMeLesson": () => ReadmeLesson(),
        "/logout": () => Logout(),
        "/showDocumentContent": () => ShowDocumentContent(),
      },
    );
  }
}
```


error:


```
════════ Exception caught by widgets library ═════════
The following assertion was thrown building Builder:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1578 pos 16: 'observer.navigator == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/mahdi/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/airoute-0.1.4/lib/route/app.dart:45:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.didUpdateWidget (package:flutter/src/widgets/navigator.dart:1578:16)
#3      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
```

**Comment by pdliuw** [comment]
** Receive your feedback, we expedited：This is an error due to your writing, not airoute ！

** Now, we have found the problem you encountered and given the following solutions：

*-*Modify your code as follows:

https://github.com/pdliuw/airoute/blob/master/example/Fix_EN.md

--Before：

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Provider.debugCheckInvalidValueType = null;

  SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]).then(
    (_) {
      runApp(
        MultiProvider(
          providers: [
            Provider<String>.value(
              value: "this is test data",
            ),
          ],
          child: OKToast(
            child: StartupApplication(),
          ),
        ),
      );
    },
  );
}

--After:

runApp(
        MultiProvider(
          providers: [
            Provider<String>.value(
              value: "this is test data",
            ),
          ],
          child: OKToast(
            child: Airoute.createMaterialApp(
              title: "Name",
              theme: ThemeData(
                fontFamily: 'IranSansLight',
                primaryColor: Color(0xFF823A84),
                accentColor: Color(0xFF823A84),
                textTheme: TextTheme(
                  title:
                      TextStyle(fontFamily: 'IranSansLight', color: Colors.black),
                ),
              ),
              home: StartupApplication(),
              routes: <String, AirouteBuilder>{
                "/LaunchPage": () => LaunchPage(),
                "/SecondPage": () => SecondPage(),
              },
            ),
          ),
        ),
      );


【https://github.com/pdliuw/airoute/blob/master/example/Fix_EN.md】A detailed problem description is documented here

**Comment by pdliuw** [comment]
Solution：

https://github.com/pdliuw/airoute/blob/master/example/Fix_EN.md

**Comment by pishguy** [comment]
@pdliuw thanks a lot, my issue resolved
